#!/bin/sh
#
ETH=`cat /etc/eth`
MAC=`cat /etc/mac`

. /etc/netinfo.sh
SRV=$Next_server
[ -n "$Option_177" ] && SRV=`echo $Option_177|cut -d : -f 1`

echo -en "\032Mc:$MAC" | nc  -p 1001 -w 1 $SRV 1001
