#!/bin/sh
#
ETH=`cat /etc/eth`
MAC=`cat /etc/mac`

. /etc/netinfo.sh
SRV=$Next_server

# get the delay on the command line
T=0
if grep -q revowait= /etc/cmdline ;then
    T=`sed -e 's/.*revowait=\([0-9]*\).*/\1/' </etc/cmdline`
fi

[ -z $T ] && exit 0
[ $T -eq 0 ] && exit 0


# get the wait value from the server
WAIT=`echo -en "T;$1;$T Mc:$MAC" | nc -p 1001 $SRV 1001`

[ -z $WAIT ] && exit 0
[ $WAIT -eq 0 ] && exit 0

# check if the previous file was a small one (< 3MB)
# if so, only wait one second.
DU=`du /tmpfs|cut -f 1`
NUMFILES=`ls /tmpfs|grep -c ^`
if [ $NUMFILES -gt 0 -a $DU -lt 3000 ]; then
    WAIT=1
fi
if [ $NUMFILES -gt 0 -a $DU -lt 30 ]; then
    exit 0
fi

sleep $WAIT
