#!/bin/sh
#
# Bug: limited to numbers 0-9 (decimal to octal conversion needs to be added)
#
ETH=`cat /etc/eth`
MAC=`cat /etc/mac`

. /etc/netinfo.sh
SRV=$Next_server
[ -n "$Option_177" ] && SRV=`echo $Option_177|cut -d : -f 1`

[ -z "$SRV" ] && exit 1

echo -en "\315\00$1Mc:$MAC" | nc -p 1001 -w 1 $SRV 1001
