#!/bin/sh
#
ETH=`cat /etc/eth`
MAC=`cat /etc/mac`

. /etc/netinfo.sh
SRV=$Next_server
[ -n "$Option_177" ] && SRV=`echo $Option_177|cut -d : -f 1`

[ -z "$SRV" ] && exit 1

if [ "$1" = "2" -o "$1" = "3" -o "$1" = "4" -o "$1" = "5" ]
then
    # Also log the image name
    N=`sed -e 's/.*revosavedir=\([^ ]*\).*/\1/' </etc/cmdline`
    N=`basename $N`
    echo -en "L${1}-${N}\0Mc:$MAC" | nc -p 1001 -w 1 $SRV 1001    
else
    echo -en "L$1Mc:$MAC" | nc -p 1001 -w 1 $SRV 1001
fi