#!/bin/sh

#fdisk -l -u /dev/hda | grep ^/dev  >/etc/diskinfo.log

ETH=`cat /etc/eth`

checkip()
{
SEC=0
# check if eth0 is up
while true                                                                      
do                                                                              
    sleep 1                                                                     
    if ifconfig $ETH|grep RUNNING >/dev/null ;then                              
	break
    else
        echo "*** $ETH: not yet configured ($SEC) ***"
	SEC=$(($SEC+1))
	if [ $SEC -gt 30 ]; then
	    echo "*** Cannot configure the NIC ***"
	    echo "Possible causes:"
	    echo "1- More than one NIC and DHCP requests are sent on the wrong NIC"
	    echo "2- No suitable driver found for the NIC"
	    echo
	    echo "Do you want to put log files on a floppy disk (y/n)"
	    read RES
	    if [ "$RES" = "y" ] ;then
		floppysave
	    fi
	    SEC=0
	    /etc/init.d/network start
	fi
	continue
    fi
    if ifconfig $ETH|grep inet.addr >/dev/null ;then
	break
    else
        echo "*** $ETH: no IP received !!! ***"
    fi
done
sleep 1
}

# get the warning message
get_warn_message()
{
    cd /etc
    /bin/atftp --tftp-timeout 1 -g -r /tftpboot/revoboot/etc/warning.txt $Next_server 69 2>/dev/null
    cd /
}

grep -q revodebug /proc/cmdline || checkip
pump -i $ETH -s >/etc/netinfo.log
sed -e "s/Device/#/" -e "s/: */=/" -e "s/	//" -e "s/ /_/g" </etc/netinfo.log >/etc/netinfo.sh

# time sync
. /etc/netinfo.sh

# LRS server IP
SRV=$Next_server
[ -n "$Option_177" ] && SRV=`echo $Option_177|cut -d : -f 1`

# IP check
if [ "$SRV" = "0.0.0.0" ]; then
    echo "*** Possible DHCP server configuration problem !"
    echo "*** Got $SRV as boot server !"
    cat /etc/netinfo.log
    sleep 60
fi

# date
echo "Getting current time from $SRV..."
rdate $SRV

# try to get the name
revogetname >/etc/lbxname

# get the warning message
get_warn_message

# Backup / Restore
grep -q revorestore /proc/cmdline && mount -t tmpfs -o size=96M tmpfs /tmpfs

# Debug ?
grep -q revodebug /proc/cmdline && exit 0

# Backup / Restore
if grep -q revosavedir /proc/cmdline ;then
    # launch initial pre-inst scripts
    if grep -q revopost /proc/cmdline ; then
	/bin/postmount
	MAC=`cat /etc/shortmac`
	echo -e "\n=== `date` ===" >> /revoinfo/$MAC/postinst.log
	/bin/doinitinst 2>&1 | tee -a /revoinfo/$MAC/postinst.log
        umount /mnt 2>/dev/null
	sleep 5
	umount /opt
	umount /revoinfo
        umount /revosave
    fi
    
    # Now backup/restore    
    if grep -q revorestore /proc/cmdline ;then
        /bin/autorestore
    else
        grep -q revopost /proc/cmdline || ( /bin/autosave ; du -k /revosave > /revosave/size.txt )
    fi
fi

# Postinstall 
if grep -q revopost /proc/cmdline ; then
    if grep -q revorestore /proc/cmdline ;then
	umount /revoinfo
	umount /revosave
    fi
    /bin/postmount
    MAC=`cat /etc/shortmac`
    echo -e "\n=== `date` ===" >> /revoinfo/$MAC/postinst.log
    /bin/dopostinst 2>&1 | tee -a /revoinfo/$MAC/postinst.log
    grep -q revodebug /proc/cmdline || umount /mnt 2>/dev/null
    sleep 5
fi


grep -q revodebug /proc/cmdline || reboot
