#!/bin/sh
PATH=/sbin:/bin:/usr/sbin:/usr/bin
# Write a reboot record to /var/log/wtmp before unmounting
halt -w
#echo -n "Deactivating swap... "
#swapoff -a
#echo "done."
echo -n "Unmounting file systems... "
umount -a
echo "done."
mount -n -o remount ro /