#!/bin/sh
#
# $Id$
#
# Linbox Rescue Server
# Copyright (C) 2005  Linbox FAS
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# --- GET BASEDIR

LBSCONF="/etc/lbs.conf"

if [ ! -f "$LBSCONF" ]; then
	echo "create_config: '$LBSCONF': File not found" >&2
	exit 1
fi

BASEDIR=$(grep -i '^ *basedir' "$LBSCONF"|tr "=" " "|awk {'print $2;'})

if [ ! -d "$BASEDIR" ]; then
	echo "create_config: '$BASEDIR': Not a directory" >&2
	exit 1
fi


PATH=$PATH:.:$BASEDIR/bin

usage()
{
    cat <<EOF
usage: $0 [option] [mac address] .. [mac address]
options:
  -b IP     Use this broadcast address instead of 255.255.255.255
EOF
}


IP=255.255.255.255

while getopts b:h? opt; do
    case "$opt" in
     "h"|"?")   usage
    	    exit ;;
     "b")     IP="$OPTARG"
    	    shift
            shift ;;
     *)     echo "Invalid argument: $opt" 1>&2
	    exit 1 ;;
    esac
done

for m in $@
do
  echo "Wake $m (IP=$IP)"
  for i in 1 2
  do
    echo "Burst $i..."
    wol -v $m
    wol -v $m -i $IP
    wol -v $m -p 80
    wol -v $m -i $IP -p 80
    wol -v $m -p 8080
    wol -v $m -i $IP -p 8080
    wol -v $m -p 1234
    wol -v $m -i $IP -p 1234
    wol -v $m -p 32767
    wol -v $m -i $IP -p 32767
  done
  sleep 1
done
