#!/usr/bin/perl

$pid = open(PIPE, "ssh -tt -o StrictHostKeyChecking=no -o Batchmode=yes root@".$ARGV[0]." 'echo \$OS;uname' |") or die $!;
eval {
    local $SIG{ALRM} = sub { die "TIMEDOUT" };
    alarm(10);
    while(<PIPE>) { print $_; };
    close(PIPE);
    alarm(0);
};
if ($@) {
    die $@ unless $@ =~ /TIMEDOUT/;
    kill 9, $pid;
    close(PIPE);  ## needed??
    $? ||= 9;
}
#print $out;
