#define HAVE_USCORE_START_SYMBOL 1
#define HAVE_USCORE_USCORE_BSS_START_SYMBOL 1
#define HAVE_EDATA_SYMBOL 1
#define HAVE_USCORE_EDATA_SYMBOL 1
#define HAVE_END_SYMBOL 1
#define HAVE_USCORE_END_SYMBOL 1

#define ADDR32 addr32
#define DATA32 data32

#define PACKAGE "LinboxBootLoader"
#define VERSION "1.33"
