#!/bin/bash
# copy the last version of .deb packages to the distribution directories
# and update the package list

DEST_ORG=../server/dist

for n in webmin-backuppc webmin-lbs-cd webmin-lbs-common webmin-lbs-inventory webmin-lbs-vnc webmin-lbs webmin-lrs-theme lrs-all
do
    echo $n
    L=`ls ${n}_*.deb|tr _ ' '|sort -n|tail -1|tr ' ' _`
    cp -av $L $DEST_ORG
done

cd $DEST_ORG
./mkpack~
