#!/bin/sh
# Packaging d'un module webmin.
# Usage: mkmodule <basename du repert du module> <tarball sans extension>
#

PKGNAME=$1

TARBALL=$2.wbm

find $PKGNAME -name \*.cgi -o -name \*.php -exec chmod 755 {} \;
tar --exclude old --exclude debian --exclude CVS --exclude .svn -cvzf $TARBALL "$PKGNAME"

echo
echo "Package: $TARBALL"
