#!/bin/bash
# copy the last version of .deb packages to the distribution directories
# and update the package list

DEST=/home/weex/ftp/base/deb/
DEST_ORG=/home/weex/lrsorg/bin/

PACK=$1
PACKD=`echo $1|tr _ -`

# find the last release
VER=`head -1 $PACK/debian/changelog|cut -f 2 -d " "|tr -d \(\)`

echo $VER

DEB=webmin-${PACKD}_${VER}_all.deb
./mkmodule $PACK $PACK
WBM=${PACK}-${VER}.wbm

#cp -av $DEB $DEST/woody
cp -av $DEB $DEST_ORG
cp -av $PACK.wbm $DEST_ORG/../webmin/$WBM

exit

