<?php
/*
 * Linbox Rescue Server - Secure Remote Control Module
 * Copyright (C) 2005	Linbox FAS
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.	See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA	02111-1307, USA.
 */


require_once(dirname(__FILE__) . "/common.inc.php"); /**< Use relative_path_to_root_module_directory function */
require_once(dirname(__FILE__) . "/utils.inc.php"); /**< Use LSC_convert_size_to_humain_readable function */
require_once(dirname(__FILE__) . "/path.inc.php"); /**< Use LSC_Path class by LSC_Widget_repository_actions */
require_once(dirname(__FILE__) . "/scheduler.inc.php"); /**< Use LSC_Scheduler class */
require_once(dirname(__FILE__) . "/state_widget.inc.php");

/**
 * This file content some HTML widget
 */
 
/**
 * Tree directory widget
 *
 * @param &$template is LSC_Tmpl class instance
 * @param &$tree_array is array generated by LSC_Tree
 * @param $url_begin this string is append to each url begining
 * @param $out_template_varname is the name template output var
 *
 * <p><strong>How to use this widget :</p>
 *
 * <pre>
 * </pre>
 *
 * @see LSC_Tree
 */
function LSC_Widget_Tree_Directory(&$template, &$tree_array, $url_begin, $out_template_varname = "tree")
{
	global $gconfig;

	$template->set_file(array(
		"tree_widget" => "widget_tree.tpl"
	));

	$template->set_block("tree_widget", "TREEITEM", "items");
	$template->set_block("tree_widget", "TREE");

	$tmp_tree_array = array("directory_list" => array($tree_array)); // I know, it's bad hack
	make_tree_recursive($template, $tmp_tree_array, $url_begin);

	$template->rename_var("SUB_DIRECTORY", "TREE");
		
	$template->parse($out_template_varname, "tree_widget", "tree_widget");
}

/*
 * Private function used only by LSC_Widget_Tree_Directory
 */
function make_tree_recursive(&$template, &$tree, $url_begin, $level = 0)
{
	$template->copy_var("TREEITEM", "TREEITEM$level");
	$template->copy_var("TREE", "TREE$level");
	$template->swap_var("TREE$level", "items", "items$level");

	foreach($tree["directory_list"] as $item) {
		$template->set_var("DIRECTORY_NAME$level", $item["name"]);
		$template->set_var("DIRECTORY_PATH$level", $url_begin . urlencode($item["path"]));
		if ($item["is_subdirectory"]) {
			if (count($item["directory_list"]) == 0) {
				$template->set_var("DIRECTORY_CLASS", " class=\"active\" ");
				$template->set_var("SUB_DIRECTORY", "");
			} else {
				make_tree_recursive($template, $item, $url_begin, $level +1);
				$template->set_var("DIRECTORY_CLASS", " class=\"open\" ");
			}
		} else {
			$template->set_var("SUB_DIRECTORY", "");
			$template->set_var("DIRECTORY_CLASS", "");
		}
		$template->rename_var("DIRECTORY_NAME$level", "DIRECTORY_NAME");
		$template->rename_var("DIRECTORY_PATH$level", "DIRECTORY_PATH");
		$template->parse("items$level", "TREEITEM$level", true);		
	}
	$template->parse("SUB_DIRECTORY", "TREE$level");
	$template->unset_var("TREE$level");
	$template->unset_var("TREEITEM$level");
	$template->unset_var("items$level");
}

/**
 * File List Directory widget
 *
 * @param &$template is LSC_Tmpl class instance
 * @param &$file_list_array is array generated by LSC_Directory
 * @param $hide_copy_and_execute_select_column is used to hide select to copy and execute column
 * @param $out_template_varname is the name template output var
 *
 * 
 * @see LSC_Directory
 */
function LSC_Widget_File_List_Directory(&$template, &$file_list_array, $hide_copy_and_execute_select_column=true, $out_template_varname = "file_list_directory")
{
	global $gconfig, $mime_type_icons_data, $mime_types_data;

	/*
	 * Open template
	 */
	$lang = $gconfig["lang"];

	$template->set_file(array(
		"widget_file_list_directory" => "widget_file_list_directory.tpl"
	));

	$template->set_var("RADIO_NOTCHECKED", "CHECKED");
	$radio_notchecked = 1;

	if ($hide_copy_and_execute_select_column) {
		/*
		 * Hide FILE_LIST_TITLE_SELECT_TO_EXECUTE_COLUMN and FILE_LIST_TITLE_SELECT_TO_EXECUTE_COLUMN 
		 */
		$template->set_block("widget_file_list_directory", "FILE_LIST_TITLE_SELECT_TO_COPY_COLUMN", "title_select_to_copy_column");
		$template->set_var("title_select_to_copy_column", "");
		
		$template->set_block("widget_file_list_directory", "FILE_LIST_TITLE_SELECT_TO_EXECUTE_COLUMN", "title_select_to_execute_column");
		$template->set_var("title_select_to_execute_column", "");
		
		/*
		 * Hide FILE_LIST_SELECT_TO_COPY_COLUMN and FILE_LIST_SELECT_TO_EXECUTE_COLUMN
		 */
		$template->set_block("widget_file_list_directory", "FILE_LIST_SELECT_TO_COPY_COLUMN", "select_to_copy_column");
		$template->set_var("select_to_copy_column", "");
		
		$template->set_block("widget_file_list_directory", "FILE_LIST_SELECT_TO_EXECUTE_COLUMN", "select_to_execute_column");
		$template->set_var("select_to_execute_column", "");
		
		/*
		 * Hide select all
		 */
		$template->set_block("widget_file_list_directory", "SELECT_ALL", "select_all");
		$template->set_var("select_all", "");
		
		
		/*
		 * Hide 4 action
		 */
		$template->set_block("widget_file_list_directory", "FOUR_ACTION", "four_action");
		$template->set_var("four_action", "");
		
		/*
		 * Show 5 action
		 */
		$template->set_block("widget_file_list_directory", "FIVE_ACTION", "five_action");
		$template->parse("five_action", "FIVE_ACTION");

	} else {
		/*
		 * Hide 5 action
		 */
		$template->set_block("widget_file_list_directory", "FIVE_ACTION", "five_action");
		$template->set_var("five_action", "");
		
		/*
		 * Show 4 action
		 */
		$template->set_block("widget_file_list_directory", "FOUR_ACTION", "four_action");
		$template->parse("four_action", "FOUR_ACTION");
	}

	/*
	 *
	 */
	$template->set_block("widget_file_list_directory", "FILE_LIST_DOWNLOAD_COLUMN", "file_list_download_column");
	$template->set_block("widget_file_list_directory", "FILE_LIST_EDIT_COLUMN", "file_list_edit_column");
	if ($hide_copy_and_execute_select_column) {
		$template->set_block("widget_file_list_directory", "FILE_LIST_EXECUTE_COLUMN", "file_list_execute_column");
	} else {
		$template->set_block("widget_file_list_directory", "FILE_LIST_EXECUTE_COLUMN_HIDE", "file_list_execute_column_hide");
	}
	$template->set_block("widget_file_list_directory", "FILE_LIST_DELETE_FILE_COLUMN", "file_list_delete_file_column");
	$template->set_block("widget_file_list_directory", "FILE_LIST_DELETE_DIRECTORY_COLUMN", "file_list_delete_directory_column");
	$template->set_block("widget_file_list_directory", "FILE_LIST_FILENAME_COLUMN", "file_list_filename_column");
	$template->set_block("widget_file_list_directory", "FILE_LIST_DIRECTORYNAME_COLUMN", "file_list_directoryname_column");
	$template->set_block("widget_file_list_directory", "FILE_LIST_ROW", "rows");

	// Set template variable for all file
	$template->set_var("RELATIVE_ROOT_MODULE_DIRECTORY", relative_path_to_root_module_directory());

	// Init list row class value
	$row_class = "row-odd";
	// Iterate all file of directory
	$i = 0;
	foreach ( $file_list_array as $file_item ) {
		$template->set_var("INDEX", $i);
		$template->set_var("FILE_LIST_ROW_CLASS", $row_class);
		if ($file_item["is_directory"]) {
			$template->set_var("FILE_LIST_ICON_MIMETYPE", "../folder.png");
			$template->set_var("FILE_LIST_MIMETYPE", "directory");
		} else {
			if (array_key_exists($file_item["extension"], $mime_type_icons_data)) {
				$template->set_var("FILE_LIST_ICON_MIMETYPE", $mime_type_icons_data[$file_item["extension"]]);
				$template->set_var("FILE_LIST_MIMETYPE", $file_item["mimetype"]);
			} else {
				$template->set_var("FILE_LIST_ICON_MIMETYPE", $mime_type_icons_data["*"]);
				$template->set_var("FILE_LIST_MIMETYPE", $file_item["mimetype"]);
			}
		}
		
		if ($file_item["is_directory"]) {
			$template->set_var("FILE_LIST_DIRECTORY_NAME", $file_item["name"]);
			$template->set_var("FILE_LIST_DIRECTORY_PATH", urlencode($file_item["name"]));
		} else {
			$template->set_var("FILE_LIST_FILENAME", $file_item["name"]);
		}
		
		if ($file_item["is_directory"]) {
			$template->set_var("FILE_LIST_SIZE", "");
			$template->set_var("FILE_LIST_HUMAN_SIZE", "");
		} else {
			$template->set_var("FILE_LIST_SIZE", $file_item["size"]);
			$template->set_var("FILE_LIST_HUMAN_SIZE", LSC_convert_size_to_humain_readable($file_item["size"]));
		}
		
		$template->set_var("FILE_LIST_CTIME", date("d-m-Y H:i", $file_item['ctime']));
		
		$template->set_var("FILE_LIST_OPEN_URL", urlencode($file_item["name"]));
		$template->set_var("FILE_LIST_EDIT_URL", urlencode($file_item["name"]));
		$template->set_var("FILE_LIST_DELETE_URL", urlencode($file_item["name"]));
		$template->set_var("FILE_LIST_EXECUTE_URL", urlencode($file_item["name"]));
		$template->set_var("FILE_LIST_PROPERTIES_URL", urlencode($file_item["name"]));

		if ($file_item["is_directory"]) {
			/*
			 * If this row is directory then I hide : download, edit, and execute action
			 */
			$template->set_var("file_list_download_column", "");
			$template->set_var("file_list_edit_column", "");
			if ($hide_copy_and_execute_select_column) {
				$template->set_var("file_list_execute_column", "");
			} else {
				$template->set_var("file_list_execute_column_hide", "");
			}
			$template->set_var("file_list_delete_file_column", "");
			$template->parse("file_list_delete_directory_column", "FILE_LIST_DELETE_DIRECTORY_COLUMN");
			$template->set_var("file_list_filename_column", "");
			$template->parse("file_list_directoryname_column", "FILE_LIST_DIRECTORYNAME_COLUMN");
		} else {
			//$template->set_block("FILE_LIST_ROW", "FILE_LIST_DOWNLOAD_COLUMN", "file_list_download_column");
			$template->parse("file_list_download_column", "FILE_LIST_DOWNLOAD_COLUMN");
			$template->parse("file_list_edit_column", "FILE_LIST_EDIT_COLUMN");
			if ($hide_copy_and_execute_select_column) {
				$template->parse("file_list_execute_column", "FILE_LIST_EXECUTE_COLUMN");
			} else {
				$template->set_var("file_list_execute_column_hide", "");
			}
			
			$template->set_var("file_list_delete_directory_column", "");
			$template->parse("file_list_delete_file_column", "FILE_LIST_DELETE_FILE_COLUMN");
			$template->set_var("file_list_directoryname_column", "");
			$template->parse("file_list_filename_column", "FILE_LIST_FILENAME_COLUMN");
		}
	
		// select the 1st .bat for execution
		$template->set_var("RADIO_CHECKED", "");
		if ($file_item["is_directory"]) {
            		$template->set_var("RADIO_CHECKED", "disabled=\"disabled\"");
                } else if (strstr($file_item["name"], ".bat") && $radio_notchecked) {
			$template->set_var("RADIO_CHECKED", "checked=\"checked\"");
			$template->set_var("RADIO_NOTCHECKED", "");
			$radio_notchecked = 0;
		}
		
		$template->parse("rows", "FILE_LIST_ROW", true);

		if ($row_class == "row-odd") $row_class = "row-even";
		else $row_class = "row-odd";

		$i++;
	}

	if ($i == 0) {
		$template->set_var("rows", "");
	}

	if ($hide_copy_and_execute_select_column) {
		$template->set_block("widget_file_list_directory", "NO_EXECUTE_FILE_SELECTED");
		$template->set_var("NO_EXECUTE_FILE_SELECTED", "");
	} else {
		$template->set_var("FILE_LIST_ROW_CLASS", $row_class);
	}

	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_file_list_directory", "widget_file_list_directory");	
}

/**
 * Where I'm connected Widget
 *
 * @param &$template is LSC_Tmpl class instance
 * @param $hostname is string value of hostname where I'm connected
 * @param $ip_address is string value of ip address where I'm connected
 * @param $out_template_varname is the name template output var
 *
 * <p><strong>How to use this widget :</p>
 *
 * <pre>
 * </pre>
 *
 */
function LSC_Widget_where_I_m_connected(&$template, $hostname, $ip_address, $profile="", $group="", $out_template_varname = "where_I_m_connected")
{
	global $gconfig;

	$lang = $gconfig["lang"];

	$template->set_file(array(
		"widget_where_I_m_connected" => "widget_where_I_m_connected.tpl"
	));

	$template->set_var("WHERE_I_M_CONNECTED_HOSTNAME", $hostname);
	$template->set_var("WHERE_I_M_CONNECTED_IP_ADDRESS", $ip_address);
	if ($profile!="") $profile=$profile.":";
	$template->set_var("WHERE_I_M_CONNECTED_PROFILE", $profile);
	if ($group!="") $group=$group."/";
	$template->set_var("WHERE_I_M_CONNECTED_GROUP", $group);

	$template->parse($out_template_varname, "widget_where_I_m_connected", "widget_where_I_m_connected");
}

/**
 * Where I'm connected group and profile Widget
 *
 * @param &$template is LSC_Tmpl class instance
 * @param $group is string value of group where I'm connected
 * @param $profile is string value of profile where I'm connected
 * @param $out_template_varname is the name template output var
 *
 * <p><strong>How to use this widget :</p>
 *
 * <pre>
 * </pre>
 *
 */
function LSC_Widget_where_I_m_connected_group_and_profile(&$template, $group, $profile, $out_template_varname = "where_I_m_connected")
{
	global $gconfig;

	$template->set_file(array(
		"widget_where_I_m_connected_group_and_profil" => "widget_where_I_m_connected_group_and_profile.tpl"
	));

	if (($group != "") && ($profile != "")) {
		/*
		 * Display group and profile
		 */
		$template->set_var("GROUP_NAME", $group);
		$template->set_var("PROFILE_NAME", $profile);
		
		/*
		 * Hide group_only and profile only
		 */
		$template->set_block("widget_where_I_m_connected_group_and_profil", "GROUP_ONLY");
		$template->set_block("widget_where_I_m_connected_group_and_profil", "PROFILE_ONLY");
		$template->set_var("GROUP_ONLY", "");
		$template->set_var("PROFILE_ONLY", "");
	} elseif ( $group != "" ) {
		/*
		 * Display group only
		 */
		$template->set_var("GROUP_NAME", $group);

		/*
		 * Hide group_only and profile_and_profil
		 */
		$template->set_block("widget_where_I_m_connected_group_and_profil", "PROFILE_ONLY");
		$template->set_block("widget_where_I_m_connected_group_and_profil", "GROUP_AND_PROFILE");
		$template->set_var("PROFILE_ONLY", "");
		$template->set_var("GROUP_AND_PROFILE", "");
	} else {
		/*
		 * Display profile only
		 */
		$template->set_var("PROFILE_NAME", $profile);

		/*
		 * Hide group_only and profile_and_profil
		 */
		$template->set_block("widget_where_I_m_connected_group_and_profil", "GROUP_ONLY");
		$template->set_block("widget_where_I_m_connected_group_and_profil", "GROUP_AND_PROFILE");
		$template->set_var("GROUP_ONLY", "");
		$template->set_var("GROUP_AND_PROFILE", "");
	}
	$template->set_var("WHERE_I_M_CONNECTED_IP_ADDRESS", $ip_address);

	$template->parse($out_template_varname, "widget_where_I_m_connected_group_and_profil", "widget_where_I_m_connected_group_and_profil");
}

/**
 * This widget display the current directory
 *
 * @param $current_directory is string value of current_directory
 *
 */
function LSC_Widget_what_is_current_directory(&$template, $current_directory, $out_template_varname = "what_is_current_directory")
{
	$template->set_file(array(
		"widget_what_is_current_directory" => "widget_what_is_current_directory.tpl"
		));

	$template->set_var("WHAT_IS_CURRENT_DIRECTORY_PATH", $current_directory);

	$template->parse($out_template_varname, "widget_what_is_current_directory", "widget_what_is_current_directory");
}

/**
 * This widget display file list directory standard action
 *
 * @param $current_directory is string value of current_directory
 *
 */
function LSC_Widget_standard_file_list_directory_actions(&$template, $current_directory, $out_template_varname = "standard_file_list_directory_actions")
{
	$template->set_file(array(
		"widget_standard_file_list_directory_actions" => "widget_standard_file_list_directory_actions.tpl"
	));

	$template->set_var("STANDARD_FILE_LIST_DIRECTORY_ACTIONS_CURRENT_DIRECTORY", $current_directory);

	$template->parse($out_template_varname, "widget_standard_file_list_directory_actions", "widget_standard_file_list_directory_actions");
}

/**
 * This widget display host standard action
 *
 * @param $current_hostname is string value of current host
 *
 */
function LSC_Widget_standard_host_actions(&$template, $script_list, $out_template_varname = "standard_host_actions")
{
	global $current_lang;

	$lang = $current_lang;

	$template->set_file(array(
		"widget_standard_host_actions" => "widget_standard_host_actions.tpl"
	));

	$template->set_block("widget_standard_host_actions", "SCRIPT_LIST", "rows");
	foreach( $script_list as $script ) {
		$template->set_var("FILENAME", $script["filename"]);
		$template->set_var("TITLE", isset($script["title".$lang]) ? $script["title".$lang] : $script["title"]);
		$template->parse("rows", "SCRIPT_LIST", true);
	}

	$template->parse($out_template_varname, "widget_standard_host_actions", "widget_standard_host_actions");
}

/**
 * This widget display repositiory action
 *
 * @param $target is string value of action target
 *
 */
function LSC_Widget_repository_actions(&$template, $param, $target, $profile = "", $group = "", $out_template_varname = "repository_actions")
{
	global $gconfig, $config;
	
	$template->set_file(array(
		"widget_repository_actions" => "widget_repository_actions.tpl"
	));
	
	$path = new LSC_Path($target);
	
	if ($path->get_host() != "") {
		$template->set_var("REPOSITORY_ACTION_HOSTNAME", $path->get_host());
		
		/*
		 * Hide some block
		 */
		$template->set_block("widget_repository_actions", "ACTION_GROUP_ONLY");
		$template->set_var("ACTION_GROUP_ONLY", "");
		
		$template->set_block("widget_repository_actions", "ACTION_PROFILE_ONLY");
		$template->set_var("ACTION_PROFILE_ONLY", "");
		
		$template->set_block("widget_repository_actions", "ACTION_GROUP_AND_PROFILE");
		$template->set_var("ACTION_GROUP_AND_PROFILE", "");
	} else {
		$template->set_var("REPOSITORY_TARGET_PROFILE", "", $profile, $group);

		/*
		 * Hide some block
		 */
		$template->set_block("widget_repository_actions", "ACTION_ON_HOST");
		$template->set_var("ACTION_ON_HOST", "");

		if (($profile == "") || ($group == "")) {
			$template->set_block("widget_repository_actions", "ACTION_GROUP_AND_PROFILE");
			$template->set_var("ACTION_GROUP_AND_PROFILE", "");
		} 
		if ($profile == "") {
			$template->set_block("widget_repository_actions", "ACTION_PROFILE_ONLY");
			$template->set_var("ACTION_PROFILE_ONLY", "");
		}
		if ($group == "") {
			$template->set_block("widget_repository_actions", "ACTION_GROUP_ONLY");
			$template->set_var("ACTION_GROUP_ONLY", "");
		}
	}
	
	$template->set_var("REPOSITORY_COMMAND_TITLE", $param["title"]);
	$template->set_var("REPOSITORY_PATH_DESTINATION", $param["path_destination"]);
	$template->set_var("MAX_CONNECTION_ATTEMPT", $param["max_connection_attempt"]);
	$template->set_var("NEXT_CONNECTION_DELAY", $param["next_connection_delay"]);
	
	if ($param["create_destination_directory"]==0) {
		$template->set_block("widget_repository_actions", "REPOSITORY_CREATE_DIRECTORY_CHECKED");
		$template->set_var("REPOSITORY_CREATE_DIRECTORY_CHECKED", "");
	} else {
		$template->set_block("widget_repository_actions", "REPOSITORY_CREATE_DIRECTORY_CHECKED");
		$template->parse("REPOSITORY_CREATE_DIRECTORY_CHECKED", "REPOSITORY_CREATE_DIRECTORY_CHECKED");
	}
	
	if ($param["start_script"]==0) {
		$template->set_block("widget_repository_actions", "REPOSITORY_START_SCRIPT_CHECKED");
		$template->set_var("REPOSITORY_START_SCRIPT_CHECKED", "");
	} else {
		$template->set_block("widget_repository_actions", "REPOSITORY_START_SCRIPT_CHECKED");
		$template->parse("REPOSITORY_START_SCRIPT_CHECKED", "REPOSITORY_START_SCRIPT_CHECKED");
	}
	
	if ($param["delete_file_after_execute_successful"]==0) {
		$template->set_block("widget_repository_actions", "REPOSITORY_DELETE_FILES_CHECKED");
		$template->set_var("REPOSITORY_DELETE_FILES_CHECKED", "");
	} else {
		$template->set_block("widget_repository_actions", "REPOSITORY_DELETE_FILES_CHECKED");
		$template->parse("REPOSITORY_DELETE_FILES_CHECKED", "REPOSITORY_DELETE_FILES_CHECKED");
	}
	
	if ($param["wake_on_lan"]==0) {
		$template->set_block("widget_repository_actions", "REPOSITORY_WAKE_ON_LAN_CHECKED");
		$template->set_var("REPOSITORY_WAKE_ON_LAN_CHECKED", "");
	} else {
		$template->set_block("widget_repository_actions", "REPOSITORY_WAKE_ON_LAN_CHECKED");
		$template->parse("REPOSITORY_WAKE_ON_LAN_CHECKED", "REPOSITORY_WAKE_ON_LAN_CHECKED");
	}

	if ($param["inventory"]==0) {
		$template->set_block("widget_repository_actions", "REPOSITORY_INVENTORY_CHECKED");
		$template->set_var("REPOSITORY_INVENTORY_CHECKED", "");
	} else {
		$template->set_block("widget_repository_actions", "REPOSITORY_INVENTORY_CHECKED");
		$template->parse("REPOSITORY_INVENTORY_CHECKED", "REPOSITORY_INVENTORY_CHECKED");
	}
	
	
	$template->parse($out_template_varname, "widget_repository_actions", "widget_repository_actions");
}

/**
 * This widget display information command detail
 *
 * @param $id_command is value of command to display
 *
 */
function LSC_Widget_command_detail(&$template, $id_command, $out_template_varname = "command_detail")
{
	global $gconfig;

	$template->set_file(array(
		"widget_command_detail" => "widget_command_detail.tpl"
	));
	
	/*
	 * Create command instance to get data
	 */
	$command = new LSC_Scheduler_Command($id_command);

	/*
	 * Give data to template
	 */
	$template->set_var("COMMAND_DATE_CREATED", $command->date_created);
	$template->set_var("COMMAND_START_FILE", $command->start_file);

	if ($command->param->parameters == "") {
		$template->set_var("COMMAND_PARAMETERS", "-");
	} else {
		$template->set_var("COMMAND_PARAMETERS", $command->parameters);
	}
	
	$template->set_var("COMMAND_PATH_DESTINATION", $command->path_destination);
	$template->set_var("COMMAND_PATH_SOURCE", $command->path_source);
	
	if ($command->create_directory_enable) {
		$template->set_var("COMMAND_CREATE_DIRECTORY", "Activé");
	} else {
		$template->set_var("COMMAND_CREATE_DIRECTORY", "Désactivé");
	}
	
	if ($command->start_script_enable) {
		$template->set_var("COMMAND_START_SCRIPT", "Activé");
	} else {
		$template->set_var("COMMAND_START_SCRIPT", "Désactivé");
	}
	
	if ($command->start_date == "0000-00-00 00:00:00") {
		$template->set_var("COMMAND_START_DATE", "-");
	} else {
		$template->set_var("COMMAND_START_DATE", $command->start_date);
	}

	if ($command->end_date == "0000-00-00 00:00:00") {
		$template->set_var("COMMAND_END_DATE", "-");
	} else {
		$template->set_var("COMMAND_END_DATE", $command->end_date);
	}
	
	$template->set_var("COMMAND_TARGET", $command->target);

	/*
	 * Give the files to template
	 */
	LSC_Widget_files_list($template, $command->files);

	/*
	 * Give the hosts to template
	 */
	$hosts_array = $command->get_host_list_dispatched();

	LSC_Widget_command_on_host_list($template, $hosts_array);

	/*
	 * Parse the template
	 */
	$template->parse($out_template_varname, "widget_command_detail", "widget_command_detail");
}

/**
 * This widget display the commands states
 *
 */
function LSC_Widget_commands_states_list(&$template, $out_template_varname = "commands_states_list")
{
	global $database, $DEBUG;
	global $gconfig;

	$template->set_file(array(
		"widget_commands_states_list" => "widget_commands_states_list.tpl"
	));
	
	/*
	 * Iterate all commands to display and send these to template
	 *
	 * Question : this query must being in LSC_Scheduler class ?
	 */
	
	$query = sprintf("
		SELECT
			id_command,
			date_created,
			start_file,
			parameters,
			path_destination,
			path_source,
			files,
			start_date,
			end_date,
			target,
			title
		FROM
			%s
		WHERE
			dispatched = \"YES\"
	",
		COMMANDS_TABLE
	);

	if (!isset($database)) {
		$database = new LSC_DB();
		if ($DEBUG >= 1) $database->Debug = true;
	}

	$database->query($query);

	if ( $database->num_rows() > 0 ) {
		$template->set_block("widget_commands_states_list", "COMMANDS_STATES_LIST_EMPTY", "commands_states_list_empty");
		$template->set_block("widget_commands_states_list", "COMMANDS_STATES_ROW", "rows");
		$template->set_var("commands_states_list_empty", "");
			
		// Init list row class value
		$row_class = "row-odd";

		// Second query level
		$q2 = new LSC_DB;
		
		// Third query
		$q3 = new LSC_DB;
		
		// Iterate command to data to template
		while ( $database->next_record() ) {
			/*
			 * Get current state value of commands on host
			 * if I found different values then I display "?"
			 */
			$query2 = sprintf("
				SELECT 
					DISTINCT(current_state)
				FROM 
					%s
				WHERE
					id_command = \"%s\"",
				COMMANDS_ON_HOST_TABLE,
				$database->f("id_command")
			);
			$q2->query($query2);
			if ($q2->num_rows() == 1) {
				$q2->next_record();
				LSC_Widget_state($template, $q2->f("current_state"), "CURRENT_STATES");
			} else {
				/*
				 * Display "?"
				 */
				$template->set_var("CURRENT_STATES", "?");
			}
			
			/*
			 * Count number of command_on_host of current command
			 */
			$query3 = sprintf(
				"
				SELECT
					COUNT(*)
				FROM
					%s
				WHERE
					id_command =\"%s\"",
				COMMANDS_ON_HOST_TABLE,
				$database->f("id_command")
			);
			$q3->query($query3);
			$q3->next_record();
			$template->set_var("NUMBER_OF_HOST", $q3->f(0));
			
			/*
			 * Send other field to template
			 */
			$template->set_var("ID_COMMAND", $database->f("id_command"));
			$template->set_var("ROW_CLASS", $row_class);
			$template->set_var("TITLE", $database->f("title"));
			$template->set_var("TARGET", $database->f("target"));
			$template->set_var("DATE_CREATED", $database->f("date_created"));
			if ($database->f("start_date") == "0000-00-00 00:00:00") {
				$template->set_var("START_DATE", "-");
			} else {
				$template->set_var("START_DATE", $database->f("start_date"));
			}
			
			if ($database->f("end_date") == "0000-00-00 00:00:00") {
				$template->set_var("END_DATE", "-");
			} else {
				$template->set_var("END_DATE", $database->f("end_date"));
			}
		
			$template->set_var("PATH_SOURCE", $database->f("path_source"));
			$template->set_var("PATH_DESTINATION", $database->f("path_destination"));
			$template->set_var("START_FILE", $database->f("start_file"));
			$template->set_var("PARAMETERS", $database->f("parameters"));
		
			$template->set_var("NUMBER_ATTEMPT", 0);
			/*
			 * Parse the row
			 */
			$template->parse("rows", "COMMANDS_STATES_ROW", true);
			/*
			 * Switch the row class
			 */
			if ($row_class == "row-odd") $row_class = "row-even";
			else $row_class = "row-odd";

			/*
			 * Clean some template variable
			 */
			$template->set_var("items", "");
		}
	} else {
		// No command to display
		debug(1, "None command to display");
		$template->set_block("widget_commands_states_list", "COMMANDS_STATES_LIST", "commands_states_list");
		$template->set_var("commands_states_list", "");
	}

	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_commands_states_list", "widget_commands_states_list");
}

/**
 * This widget diplay the list of file
 *
 * @param $files_array is the datas to display (get this data from LSC_Command->get_host_list_dispatched()
 *
 * @see LSC_Command->get_host_list_dispatched
 */
function LSC_Widget_files_list(&$template, &$files_array, $out_template_varname="files_list")
{
	global $gconfig;

	$template->set_file(array(
		"widget_files_list" => "widget_files_list.tpl"
	));

	
	$template->set_block("widget_files_list", "FILES_LIST_ROW", "rows");
	// Init list row class value
	$row_class = "row-odd";

	/*
	 * Iterate all element of files_array
	 */
	$i = 0;
	foreach($files_array as $file) {
		$i++;
		
		$template->set_var("ROW_CLASS", $row_class);
		
		$template->set_var("INDEX", $i);
		$template->set_var("FILENAME", $file);

		$template->parse("rows", "FILES_LIST_ROW", true);
		/*
		 * Switch the row class
		 */
		if ($row_class == "row-odd") $row_class = "row-even";
		else $row_class = "row-odd";
	}

	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_files_list", "widget_files_list");

	/*
	 * Clean some template variable
	 */
	$template->set_var("rows", "");
}

/**
 * This widget diplay the list of states hosts
 *
 * @param $hosts_array is the datas to display
 *
 */
function LSC_Widget_hosts_states_list(&$template, &$hosts_array, $out_template_varname="hosts_list")
{
	global $gconfig;

	$template->set_file(array(
		"widget_hosts_list" => "widget_hosts_states_list.tpl"
	));
	
	$template->set_block("widget_hosts_list", "HOSTS_LIST_ROW", "rows");
	// Init list row class value
	$row_class = "row-odd";

	/*
	 * Iterate all element of files_array
	 */
	$i = 0;
	foreach($hosts_array as $host) {
		$i++;
		$template->set_var("INDEX", $i);
		
		$template->set_var("ROW_CLASS", $row_class);

		$template->set_var("ID_COMMAND_ON_HOST", $host["id_command_on_host"]);
		$template->set_var("HOSTNAME", $host["hostname"]);
		$template->set_var("CURRENT_STATE", $host["current_state"]);
		$template->set_var("UPLOADED", $host["uploaded"]);
		$template->set_var("EXECUTED", $host["executed"]);
		$template->set_var("DELETED", $host["deleted"]);

		$template->parse("rows", "HOSTS_LIST_ROW", true);
		/*
		 * Switch the row class
		 */
		if ($row_class == "row-odd") $row_class = "row-even";
		else $row_class = "row-odd";
	}
		
	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_hosts_states_list", "widget_hosts_states_list");
}

/**
 * This widget display information command on host detail
 *
 * @param $id_command_on_host is value of command on host to display
 *
 */
function LSC_Widget_command_on_host_detail(&$template, $id_command_on_host, $out_template_varname = "command_on_host_detail")
{
	global $gconfig;

	$template->set_file(array(
		"widget_command_on_host_detail" => "widget_command_on_host_detail.tpl"
	));
	
	/*
	 * Create command and command on host instance to get data
	 */
	$command_on_host = new LSC_Scheduler_Command_on_Host($id_command_on_host);

	$command = new LSC_Scheduler_Command($command_on_host->id_command);

	/*
	 * Give data to template
	 */
	$template->set_var("COMMAND_DATE_CREATED", $command->date_created);
	$template->set_var("COMMAND_START_FILE", $command->start_file);

	if ($command->param->parameters == "") {
		$template->set_var("COMMAND_PARAMETERS", "-");
	} else {
		$template->set_var("COMMAND_PARAMETERS", $command->parameters);
	}
	
	$template->set_var("COMMAND_PATH_DESTINATION", $command->path_destination);
	$template->set_var("COMMAND_PATH_SOURCE", $command->path_source);
	
	if ($command->create_directory_enable) {
		$template->set_var("COMMAND_CREATE_DIRECTORY", "Activé");
	} else {
		$template->set_var("COMMAND_CREATE_DIRECTORY", "Désactivé");
	}
	
	if ($command->start_script_enable) {
		$template->set_var("COMMAND_START_SCRIPT", "Activé");
	} else {
		$template->set_var("COMMAND_START_SCRIPT", "Désactivé");
	}
	
	if ($command->start_date == "0000-00-00 00:00:00") {
		$template->set_var("COMMAND_START_DATE", "-");
	} else {
		$template->set_var("COMMAND_START_DATE", $command_on_host->start_date);
	}

	if ($command->end_date == "0000-00-00 00:00:00") {
		$template->set_var("COMMAND_END_DATE", "-");
	} else {
		$template->set_var("COMMAND_END_DATE", $command_on_host->end_date);
	}
	
	$template->set_var("COMMAND_HOSTNAME", $command_on_host->host);
	$template->set_var("ID_COMMAND_ON_HOST", $id_command_on_host);
	$template->set_var("ID_COMMAND", $command_on_host->id_command);

	// States
	$template->set_var("CURRENT_STATE", $command_on_host->current_state);
	$template->set_var("CURRENT_UPLOADED", $command_on_host->uploaded);
	$template->set_var("CURRENT_EXECUTED", $command_on_host->executed);
	$template->set_var("CURRENT_DELETED", $command_on_host->deleted);
	
	/*
	 * Give the files to template
	 */
	LSC_Widget_files_list($template, $command->files);

	/*
	 * Give the history to template
	 */
	$history_array = $command_on_host->get_history_list();

	LSC_Widget_command_on_host_history($template, $history_array);

	/*
	 * Parse the template
	 */
	$template->parse($out_template_varname, "widget_command_on_host_detail", "widget_command_on_host_detail");
}

/**
 * This widget display the list of command on host history
 *
 * @param $history_array is datas to display
 *
 * @see LSC_Scheduler_Command_on_Host class get_history_list method
 *
 * Use widget_command_on_host_history.tpl template
 */
function LSC_Widget_command_on_host_history(&$template, &$history_array, $out_template_varname="command_on_host_history")
{
	global $gconfig;

	$template->set_file(array(
		"widget_command_on_host_history" => "widget_command_on_host_history.tpl"
	));
	
	$template->set_block("widget_command_on_host_history", "COMMAND_ON_HOST_HISTORY_ROW", "rows");
	// Init list row class value
	$row_class = "row-odd";

	/*
	 * Iterate all element of history_array
	 */
	$i = 0;
	foreach($history_array as $history) {
		$i++;
		$template->set_var("INDEX", $i);
		
		$template->set_var("ROW_CLASS", $row_class);

		$template->set_var("ID_COMMAND_HISTORY", $history["id_command_history"]);
		$template->set_var("DATE", $history["date"]);
		$template->set_var("STATE", $history["state"]);
		$template->set_var("STDOUT", $history["stdout"]);
		$template->set_var("STDERR", $history["stderr"]);

		$template->parse("rows", "COMMAND_ON_HOST_HISTORY_ROW", true);

		/*
		 * Switch the row class
		 */
		if ($row_class == "row-odd") $row_class = "row-even";
		else $row_class = "row-odd";
	}
		
	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_command_on_host_history", "widget_command_on_host_history");
	
}

/**
 * Widget to display action message (error or success mode)
 *
 * @param $message (string) = message to display
 * @param $error (boolean) = true if error message else success message
 *
 */
function LSC_Widget_action_message(&$template, $message, $error, $out_template_varname = "action_message")
{
	global $gconfig;

	$template->set_file(array(
		"widget_action_message" => "widget_action_message.tpl"
	));
	
	$template->set_var("ACTION_MESSAGE_CONTENT", $message);

	if ($error) {
		$template->set_block("widget_action_message", "ACTION_MESSAGE_SUCCESS");
		$template->set_var("ACTION_MESSAGE_SUCCESS", "");
	} else {
		$template->set_block("widget_action_message", "ACTION_MESSAGE_ERROR");
		$template->set_var("ACTION_MESSAGE_ERROR", "");
	}

	$template->parse($out_template_varname, "widget_action_message", "widget_action_message");
}

/**
 * This widget diplay the hosts list
 *
 * @param $hosts_array is the datas to display
 *
 */
function LSC_Widget_hosts_list(&$template, &$hosts_array, $out_template_varname="hosts_list")
{
	global $gconfig;

	$template->set_file(array(
		"widget_hosts_list" => "widget_hosts_list.tpl"
	));
	
	$template->set_block("widget_hosts_list", "HOSTS_LIST_ROW", "rows");
	// Init list row class value
	$row_class = "row-odd";

	/*
	 * Iterate all element of files_array
	 */
	$i = 0;
	foreach($hosts_array as $host) {
		$i++;
		$template->set_var("INDEX", $i);
		
		$template->set_var("ROW_CLASS", $row_class);

		$template->set_var("HOSTNAME", $host["hostname"]);
		$template->set_var("IP", $host["ip"]);
		$template->set_var("MAC", $host["mac"]);
		$template->set_var("MAC_AND_DOT", urlencode($host["mac"]));

		$template->parse("rows", "HOSTS_LIST_ROW", true);
		/*
		 * Switch the row class
		 */
		if ($row_class == "row-odd") $row_class = "row-even";
		else $row_class = "row-odd";
	}
		
	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_hosts_list", "widget_hosts_list");
}

/**
 * This widget diplay the command on host list
 *
 * @param $command_on_host_array is the datas to display
 *
 */
function LSC_Widget_command_on_host_list(&$template, &$command_on_host_array, $out_template_varname="hosts_list")
{
	global $gconfig;

	$template->set_file(array(
		"widget_command_on_host_list" => "widget_command_on_host_list.tpl"
	));
	
	$template->set_block("widget_command_on_host_list", "HOSTS_LIST_ROW", "rows");
	// Init list row class value
	$row_class = "row-odd";

	/*
	 * Iterate all element of files_array
	 */
	$i = 0;
	foreach($command_on_host_array as $host) {
		$i++;
		$template->set_var("INDEX", $i);
		
		$template->set_var("ROW_CLASS", $row_class);

		$template->set_var("HOSTS_LIST_HOSTNAME", $host["hostname"]);
		$template->set_var("HOSTS_LIST_IP", $host["ip"]);
		$template->set_var("HOSTS_LIST_MAC", $host["mac"]);
		$template->set_var("HOSTS_LIST_MAC_AND_DOT", urlencode($host["mac"]));
		$template->set_var("HOSTS_LIST_ID_COMMAND_ON_HOST", $host["id_command_on_host"]);
		
		$template->set_var("HOSTS_LIST_CURRENT_STATES", return_html_state($host["current_state"]));

		$template->parse("rows", "HOSTS_LIST_ROW", true);
		/*
		 * Switch the row class
		 */
		if ($row_class == "row-odd") $row_class = "row-even";
		else $row_class = "row-odd";
	}
		
	/*
	 * Display template
	 */
	$template->parse($out_template_varname, "widget_command_on_host_list", "widget_command_on_host_list");
}

?>
